"""delete years and sex

Revision ID: ed79e53713ea
Revises: b01993896ab9
Create Date: 2025-07-12 17:37:50.757835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed79e53713ea"
down_revision: Union[str, Sequence[str], None] = "b01993896ab9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.drop_column("users", "years")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("years", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "gender",
            postgresql.ENUM("MALE", "FEMALE", name="genderenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
