"""fix price in OrderItem

Revision ID: b01993896ab9
Revises: 4836261b6b8c
Create Date: 2025-07-08 17:46:05.730763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b01993896ab9"
down_revision: Union[str, Sequence[str], None] = "4836261b6b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_items", sa.Column("price", sa.Float(), nullable=False))
    op.drop_column("order_items", "price_per_item")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items",
        sa.Column(
            "price_per_item",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("order_items", "price")
    # ### end Alembic commands ###
