"""Added account table

Revision ID: 4836261b6b8c
Revises:
Create Date: 2025-07-08 03:21:10.284553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4836261b6b8c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", name="genderenum"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("years", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "years")
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
